package Connection.Telas;
import Connection.Classes.doacoes;

import bancodesangue.MySql.doacoesdao;
import java.sql.SQLException;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;


/**
 *
 * @author sabino
 */
public class CrudDoacao extends javax.swing.JFrame {

    doacoes d = new doacoes();
    doacoesdao ddao = new doacoesdao();
    
    public CrudDoacao(){
        initComponents();
    }
    
   
    public void ViewJTable() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelacrud.getModel();
        tabelacrud.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelacrud.getModel();
        modelo.setNumRows(0);
        
        
        for (doacoes d : ddao.read()){

            modelo.addRow(new Object[]{
             
             d.getRG(),
             d.getData(),
             d.getHorario(),
             d.getColetor()
            

    });
                    }
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
   
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btnremover = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        lblRG = new javax.swing.JLabel();
        lbldatadoacao = new javax.swing.JLabel();
        lblhorario = new javax.swing.JLabel();
        lblcoletor = new javax.swing.JLabel();
        jTextField1Horario = new javax.swing.JTextField();
        jTextField3RG = new javax.swing.JTextField();
        jTextField4DataDeDoacao = new javax.swing.JTextField();
        jTextFieldcoletor = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelacrud = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Doação");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnatualizar.setText("Atualizar");
        btnatualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        btnremover.setText("Remover");
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        lblRG.setText("RG");

        lbldatadoacao.setText("Data da Doação");

        lblhorario.setText("Horário");

        lblcoletor.setText("Coletor");

        jTextFieldcoletor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldcoletorActionPerformed(evt);
            }
        });

        tabelacrud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelacrud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "RG", "Telefone", "Data última Doação", "Coletor"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(tabelacrud);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(53, 53, 53)
                        .addComponent(btnatualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnremover)
                        .addGap(76, 76, 76)
                        .addComponent(btncancelar)
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblRG)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcoletor)
                                    .addComponent(jTextFieldcoletor, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(lbldatadoacao)
                                        .addGap(18, 18, 18)
                                        .addComponent(lblhorario))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField4DataDeDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jTextField1Horario, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField3RG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblRG)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField3RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbldatadoacao)
                    .addComponent(lblhorario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4DataDeDoacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1Horario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblcoletor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldcoletor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovo)
                    .addComponent(btnatualizar)
                    .addComponent(btnremover)
                    .addComponent(btncancelar))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        salvarnobanco();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jTextFieldcoletorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldcoletorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldcoletorActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
        atualizarnobanco();
      
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
    deletarnobanco();
    }//GEN-LAST:event_btnremoverActionPerformed
private boolean Validar(){
            return (jTextField1Horario.getText().equals("")
                    || jTextField3RG.getText().equals("")
                    || jTextField4DataDeDoacao.getText().equals(""))
                    || jTextFieldcoletor.getText().equals("");
        }

private void salvarnobanco(){
      if(Validar()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    }else{
          try{
          d.setRG(Integer.parseInt(jTextField3RG.getText()));
          d.setData(jTextField4DataDeDoacao.getText());
          d.setHorario(jTextField1Horario.getText());
          d.setColetor(Integer.parseInt(jTextFieldcoletor.getText()));
          
          ddao.criarRegistroNoBancoDeDados(d);
          }catch(SQLException e){
             JOptionPane.showMessageDialog(null, "Preencha todos os campos!" +e.toString()); 
          }
          readJTable();
      }
}

private void deletarnobanco(){
            if (tabelacrud.getSelectedRow() != -1) {

            d.setId((int) tabelacrud.getValueAt(tabelacrud.getSelectedRow(), 0));
            
            ddao.deletarRegistroNoBancoDeDados(d);
            
           jTextField1Horario.setText("");
           jTextField3RG.setText("");
           jTextField4DataDeDoacao.setText("");
           jTextFieldcoletor.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Coloque o doacao que deseja excluir.");
        }   
}

private void atualizarnobanco(){
            if (tabelacrud.getSelectedRow() != -1) {

            d.setRG(Integer.parseInt(jTextField3RG.getText()));
            d.setData(jTextField4DataDeDoacao.getText());
            d.setHorario(jTextField1Horario.getText());
            d.setColetor(Integer.parseInt(jTextFieldcoletor.getText()));    
            d.setId((int) tabelacrud.getValueAt(tabelacrud.getSelectedRow(), 0));
            ddao.update(d);

            jTextField1Horario.setText("");
           jTextField3RG.setText("");
           jTextField4DataDeDoacao.setText("");
           jTextFieldcoletor.setText("");
            readJTable();

            }
}


    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudDoacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudDoacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnremover;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1Horario;
    private javax.swing.JTextField jTextField3RG;
    private javax.swing.JTextField jTextField4DataDeDoacao;
    private javax.swing.JTextField jTextFieldcoletor;
    private javax.swing.JLabel lblRG;
    private javax.swing.JLabel lblcoletor;
    private javax.swing.JLabel lbldatadoacao;
    private javax.swing.JLabel lblhorario;
    private javax.swing.JTable tabelacrud;
    // End of variables declaration//GEN-END:variables
}
