package Connection.Telas;
import Connection.Classes.doadores;
import bancodesangue.MySql.doadoresdao;
import java.sql.SQLException;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;





/**
 *
 * @author sabino
 */
public class CrudDoador extends javax.swing.JFrame {

    doadores d = new doadores();
    doadoresdao ddao = new doadoresdao();
    public CrudDoador(){
        initComponents();
        
    }
    
    /**
     *
     */
    public void ViewJTable() {
        initComponents();
        DefaultTableModel modelo = (DefaultTableModel) tabelacrud.getModel();
        tabelacrud.setRowSorter(new TableRowSorter(modelo));

        readJTable();

    }
    public void readJTable() {
        
        DefaultTableModel modelo = (DefaultTableModel) tabelacrud.getModel();
        modelo.setNumRows(0);
        
        
        for (doadores doador : ddao.read()){

            modelo.addRow(new Object[]{
              doador.getNome(),
              doador.getRG(),
              doador.getIdade(),
              doador.getTelefone(),
              doador.getTiposangue(),
              doador.getEndereco(),
              doador.getEmail()

    });
                    }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
   
    
   
     
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        btnNovo = new javax.swing.JButton();
        btnatualizar = new javax.swing.JButton();
        btnremover = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        jlblnome = new javax.swing.JLabel();
        lblRG = new javax.swing.JLabel();
        JlabelTipo = new javax.swing.JLabel();
        JlabelIdade = new javax.swing.JLabel();
        JlabelEndereco = new javax.swing.JLabel();
        jTextField1idade = new javax.swing.JTextField();
        jTextFieldnome = new javax.swing.JTextField();
        jTextField3RG = new javax.swing.JTextField();
        jTextField4tipo = new javax.swing.JTextField();
        jTextFieldendereco = new javax.swing.JTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        tabelacrud = new javax.swing.JTable();
        jTextFieldtelefone = new javax.swing.JTextField();
        jLabeltelefone = new javax.swing.JLabel();
        Jlabelemail = new javax.swing.JLabel();
        jTextEmail = new javax.swing.JTextField();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Cadastro de Doador");

        btnNovo.setText("Novo");
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });

        btnatualizar.setText("Atualizar");
        btnatualizar.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        btnatualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatualizarActionPerformed(evt);
            }
        });

        btnremover.setText("Remover");
        btnremover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnremoverActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        jlblnome.setText("Nome");

        lblRG.setText("RG");

        JlabelTipo.setText("Tipo Sanguineo");

        JlabelIdade.setText("Idade");

        JlabelEndereco.setText("Endereço");

        jTextFieldendereco.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldenderecoActionPerformed(evt);
            }
        });

        tabelacrud.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tabelacrud.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "RG", "Tipo Sangue", "Idade", "Telefone", "Endereço", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tabelacrud.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                tabelacrudAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });
        jScrollPane3.setViewportView(tabelacrud);

        jLabeltelefone.setText("Telefone");

        Jlabelemail.setText("Email");

        jTextEmail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextEmailActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 515, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jTextFieldendereco, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jTextFieldnome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
                                .addComponent(jlblnome, javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTextField4tipo, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JlabelTipo))
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(JlabelIdade)
                                        .addComponent(jTextField1idade, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(JlabelEndereco))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Jlabelemail)
                            .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRG)
                            .addComponent(jTextField3RG, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabeltelefone)
                            .addComponent(jTextEmail))))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnNovo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(57, 57, 57)
                .addComponent(btnatualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnremover)
                .addGap(67, 67, 67)
                .addComponent(btncancelar)
                .addGap(28, 28, 28))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlblnome)
                    .addComponent(lblRG))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField3RG, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelTipo)
                    .addComponent(JlabelIdade)
                    .addComponent(jLabeltelefone))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField4tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldtelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(JlabelEndereco)
                    .addComponent(Jlabelemail))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btncancelar)
                    .addComponent(btnremover)
                    .addComponent(btnatualizar)
                    .addComponent(btnNovo))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        salvarnobanco();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        this.dispose(); 
      
    }//GEN-LAST:event_btncancelarActionPerformed

    private void jTextFieldenderecoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldenderecoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldenderecoActionPerformed

    private void btnatualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatualizarActionPerformed
    atualizarnobanco();
      
    }//GEN-LAST:event_btnatualizarActionPerformed

    private void jTextEmailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextEmailActionPerformed
       
    }//GEN-LAST:event_jTextEmailActionPerformed

    private void btnremoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnremoverActionPerformed
         deletarnobanco();
    }//GEN-LAST:event_btnremoverActionPerformed

    private void tabelacrudAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_tabelacrudAncestorAdded
    
    }//GEN-LAST:event_tabelacrudAncestorAdded
private boolean Validar(){
            return (jTextField1idade.getText().equals("")
                    || jTextFieldnome.getText().equals("")
                    || jTextField3RG.getText().equals("")
                    || jTextField4tipo.getText().equals(""))
                    || jTextFieldendereco.getText().equals("");
        }

private void salvarnobanco(){
      if(Validar()){
            JOptionPane.showMessageDialog(null, "Preencha todos os campos!");
    }else{
          try{
          d.setNome(jTextFieldnome.getText());
          d.setRG(Integer.parseInt(jTextField3RG.getText()));
          d.setEndereco(jTextFieldendereco.getText());
          d.setIdade(jTextField1idade.getText());
          d.setEmail(jTextEmail.getText());
          d.setTelefone(jTextFieldtelefone.getText());
          d.setTiposangue(jTextField4tipo.getText());
          
          ddao.criarRegistroNoBancoDeDados(d);
          
          }catch(SQLException e){
             JOptionPane.showMessageDialog(null, "Preencha todos os campos!" +e.toString()); 
          }
          readJTable();
          
}
      
}

private void deletarnobanco(){
            if (tabelacrud.getSelectedRow() != -1) {

            d.setRG((int) tabelacrud.getValueAt(tabelacrud.getSelectedRow(), 0));
            
            ddao.deletarRegistroNoBancoDeDados(d);
            
            jTextField1idade.setText("");
            jTextFieldnome.setText("");
            jTextField3RG.setText("");
            jTextField4tipo.setText("");
            jTextFieldendereco.setText("");
            jTextEmail.setText("");
            jTextFieldtelefone.setText("");

            readJTable();

        } else {
            JOptionPane.showMessageDialog(null, "Coloque o doador que deseja excluir.");
        }   
}

private void atualizarnobanco(){
            if (tabelacrud.getSelectedRow() != -1) {

            

            d.setNome(jTextFieldnome.getText());
            d.setEndereco(jTextFieldendereco.getText());
            d.setIdade(jTextField1idade.getText());
            d.setEmail(jTextEmail.getText());
            d.setTelefone(jTextFieldtelefone.getText());
            d.setTiposangue(jTextField4tipo.getText());
            d.setRG((int) tabelacrud.getValueAt(tabelacrud.getSelectedRow(), 0));
            ddao.update(d);

            jTextField1idade.setText("");
            jTextFieldnome.setText("");
            jTextField3RG.setText("");
            jTextField4tipo.setText("");
            jTextFieldendereco.setText("");
            jTextEmail.setText("");
            jTextFieldtelefone.setText("");
            readJTable();

            }
}



    /**
     *
     */


    

    

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrudDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrudDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrudDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrudDoador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrudDoador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel JlabelEndereco;
    private javax.swing.JLabel JlabelIdade;
    private javax.swing.JLabel JlabelTipo;
    private javax.swing.JLabel Jlabelemail;
    private javax.swing.JButton btnNovo;
    private javax.swing.JButton btnatualizar;
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnremover;
    private javax.swing.JLabel jLabeltelefone;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextEmail;
    private javax.swing.JTextField jTextField1idade;
    private javax.swing.JTextField jTextField3RG;
    private javax.swing.JTextField jTextField4tipo;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldtelefone;
    private javax.swing.JLabel jlblnome;
    private javax.swing.JLabel lblRG;
    private javax.swing.JTable tabelacrud;
    // End of variables declaration//GEN-END:variables
}
